{% set name = "mecab-python3" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/mecab-python3-{{ version }}.tar.gz
  sha256: 70988bab263696456f75d3d8910c75aea477a9d08054ad7ef85be5470dd3f65b

build:
  number: 2
  entry_points:
    - mecab-py = MeCab.cli:parse
    - mecab-py-info = MeCab.cli:info
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools_scm
    - setuptools
    - mecab
  run:
    - python
    - mecab

test:
  imports:
    - MeCab
  commands:
    - pip check
    - mecab-py-info
  requires:
    - pip
    - unidic-lite

about:
  home: https://github.com/SamuraiT/mecab-python3
  summary: Python wrapper for the MeCab morphological analyzer for Japanese
  license: GPL-2.0-only OR LGPL-2.1-only OR BSD-3-Clause
  license_file:
    - COPYING
    - GPL
    - LGPL
    - BSD

extra:
  recipe-maintainers:
    - rynorris
    - henry-thompson
